import keyMirror from 'keymirror';


export const GeneralJournal = keyMirror({
    GET_GENERAL_JOURNAL_LIST_REQUEST: null,
    GET_GENERAL_JOURNAL_LIST_SUCCESS: null,
    GET_GENERAL_JOURNAL_LIST_ERROR: null,
    POST_GENERAL_JOURNAL_ENTRY_REQUEST: null,
    POST_GENERAL_JOURNAL_ENTRY_SUCCESS: null,
    POST_GENERAL_JOURNAL_ENTRY_ERROR: null,
    GENERAL_JOURNAL_LOADING: null,
    SET_FORM_MODAL_ACTIVE_STATUS: null,
})